[package]
name = "wasmtime_reducer"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["staticlib"]

[dependencies]
ms_std = { path = "../../ms_std", features = ["panic_def", "alloc_def"] }
ms_hostcall = { path = "../../ms_hostcall" }
wasmtime_wasi_api = { path = "../../wasmtime_wasi_api" }

lazy_static = { version = "1.5.0", features = ["spin_no_std"] }
spin = "0.9.8"

[features]
mpk = ["ms_std/mpk"]
