[package]
name = "handler"
version = "0.1.0"
authors = ["Piotr Roslaniec <p.roslaniec@gmail.com>"]
edition = "2018"

[dependencies]
hashbrown = "0.14.2"
redis = "0.23.3"
rust-s3 = { git = "https://github.com/durch/rust-s3", default-features = false, features = [
    "sync",
    "sync-rustls-tls",
] }
serde = "1.0.190"
serde_json = "1.0.108"
