name: CI

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs: 
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout github repo
        uses: actions/checkout@v2
        # with:
        #   lfs: true
      # - name: Checkout LFS objects
      #   run: git lfs checkout
      # - run: mkdir fs_images
      # - name: pull Fatfs image
      #   uses: schmiddim/action-wget-unzip@v2
      #   with:
      #     url: 'http://47.92.106.203:3306/fatfs.zip'
      #     destination: fs_images/
      - run: unzip fs_images/fatfs.zip -d fs_images
      - run: ls -alh fs_images && realpath fs_images/fatfs.img
      - name: install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2024-08-02
          override: true
      - name: Build
        run: cargo build --workspace && ./scripts/build_all_common.sh && ./scripts/build_user.sh
      - name: Rust Test
        run: RUST_BACKTRACE=1 cargo test -p libmsvisor